(() => {
  const ROOT_ID = "yt-subtitle-txt-root";
  const REQUEST_EVENT = "yt-subtitle-txt-request";
  const RESPONSE_EVENT = "yt-subtitle-txt-response";
  const CAPTION_EVENT = "yt-subtitle-txt-caption";
  const core = globalThis.YouTubeSubtitleCore;

  let playerResponse = null;
  let tracks = [];
  let segments = [];
  let currentVideoId = "";
  let capturedCaptions = [];

  document.addEventListener(CAPTION_EVENT, (event) => {
    try {
      const item = JSON.parse(event.detail);
      if (!capturedCaptions.some((old) => old.url === item.url && old.text === item.text)) capturedCaptions.push(item);
    } catch {
      // Ignore malformed messages from the page world.
    }
  });

  function h(tag, attributes = {}, children = []) {
    const element = document.createElement(tag);
    for (const [key, value] of Object.entries(attributes)) {
      if (key === "className") element.className = value;
      else if (key === "text") element.textContent = value;
      else if (key.startsWith("on") && typeof value === "function") {
        element.addEventListener(key.slice(2).toLowerCase(), value);
      } else if (value !== undefined && value !== null) {
        element.setAttribute(key, value);
      }
    }
    element.append(...children);
    return element;
  }

  function isWatchPage() {
    return location.pathname === "/watch" && Boolean(new URL(location.href).searchParams.get("v"));
  }

  function getVideoId() {
    return new URL(location.href).searchParams.get("v") || "";
  }

  function setStatus(text, kind = "idle") {
    const status = document.querySelector(`#${ROOT_ID} [data-role="status"]`);
    if (!status) return;
    status.textContent = text;
    status.dataset.kind = kind;
  }

  function setBusy(busy) {
    document.querySelectorAll(`#${ROOT_ID} button, #${ROOT_ID} select`).forEach((control) => {
      if (!control.matches("[data-role='close']")) control.disabled = busy;
    });
  }

  function setOutput(text) {
    const output = document.querySelector(`#${ROOT_ID} [data-role="output"]`);
    if (output) output.value = text;
  }

  function timestampsEnabled() {
    return Boolean(document.querySelector(`#${ROOT_ID} [data-role="timestamps"]`)?.checked);
  }

  function refreshOutput() {
    setOutput(core.buildPlainText(segments, timestampsEnabled()));
  }

  function requestPlayerResponse(timeoutMs = 3000) {
    return new Promise((resolve) => {
      let settled = false;
      const finish = (response) => {
        if (settled) return;
        settled = true;
        document.removeEventListener(RESPONSE_EVENT, onResponse);
        resolve(response);
      };
      const onResponse = (event) => {
        try {
          const state = event.detail ? JSON.parse(event.detail) : null;
          if (Array.isArray(state?.capturedCaptions)) capturedCaptions = state.capturedCaptions;
          finish(state?.playerResponse || state);
        } catch {
          finish(null);
        }
      };
      document.addEventListener(RESPONSE_EVENT, onResponse, { once: true });
      document.dispatchEvent(new CustomEvent(REQUEST_EVENT));
      setTimeout(() => finish(null), timeoutMs);
    });
  }

  function renderTrackOptions() {
    const select = document.querySelector(`#${ROOT_ID} [data-role="language"]`);
    if (!select) return;
    select.replaceChildren();
    tracks.forEach((track, index) => {
      const suffix = track.autoGenerated ? "（自动生成）" : "";
      select.append(h("option", { value: String(index), text: `${track.label}${suffix}` }));
    });
    select.disabled = tracks.length < 2;
  }

  function findCapturedCaption(track) {
    const videoId = getVideoId();
    return [...capturedCaptions].reverse().find((item) => {
      try {
        const url = new URL(item.url, location.href);
        return url.searchParams.get("v") === videoId && url.searchParams.get("lang") === track.languageCode;
      } catch {
        return false;
      }
    });
  }

  async function loadTrack(trackIndex) {
    const track = tracks[Number(trackIndex)];
    if (!track) throw new Error("没有可读取的字幕轨道");

    setBusy(true);
    setStatus(`正在读取 ${track.label}…`, "loading");
    try {
      const response = await fetch(core.withFormat(track.baseUrl, "json3"), { credentials: "include" });
      if (!response.ok) throw new Error(`字幕请求失败（HTTP ${response.status}）`);
      const text = await response.text();
      try {
        segments = core.parseJson3(JSON.parse(text));
      } catch {
        segments = [];
      }
      if (!segments.length) {
        const vttResponse = await fetch(core.withFormat(track.baseUrl, "vtt"), { credentials: "include" });
        if (vttResponse.ok) segments = core.parseVtt(await vttResponse.text());
      }
      if (!segments.length) {
        await requestPlayerResponse(1000);
        const captured = findCapturedCaption(track);
        if (captured) {
          try {
            segments = core.parseJson3(JSON.parse(captured.text));
          } catch {
            segments = core.parseVtt(captured.text);
          }
        }
      }
      if (!segments.length) throw new Error("字幕轨道为空");
      refreshOutput();
      setStatus(`已读取 ${segments.length} 条 · ${track.label}`, "ok");
    } finally {
      setBusy(false);
    }
  }

  async function loadAvailableTracks() {
    if (!isWatchPage()) throw new Error("请先打开一个 YouTube 视频页面");
    setBusy(true);
    setStatus("正在读取视频字幕信息…", "loading");
    try {
      playerResponse = await requestPlayerResponse();
      tracks = core.extractTracks(playerResponse);
      if (!tracks.length) {
        throw new Error("这个视频没有可用字幕，或字幕尚未加载；可尝试刷新页面后重试");
      }
      renderTrackOptions();
      await loadTrack(0);
    } finally {
      setBusy(false);
    }
  }

  function getMetadata() {
    const details = playerResponse?.videoDetails || {};
    const title = details.title || document.title.replace(/\s*-\s*YouTube\s*$/, "") || "YouTube 字幕";
    const author = details.author || document.querySelector("#channel-name a")?.textContent?.trim() || "";
    const select = document.querySelector(`#${ROOT_ID} [data-role="language"]`);
    const track = tracks[Number(select?.value || 0)];
    return { title, author, track };
  }

  function exportText() {
    if (!segments.length) throw new Error("请先读取字幕");
    const { title, author, track } = getMetadata();
    const body = core.buildPlainText(segments, timestampsEnabled());
    return [
      title,
      author ? `频道：${author}` : "",
      `语言：${track?.label || "未知"}${track?.autoGenerated ? "（自动生成）" : ""}`,
      `来源：${location.href}`,
      "",
      body,
    ].filter((line, index) => line || index >= 4).join("\n");
  }

  async function copyTranscript() {
    const text = exportText();
    await navigator.clipboard.writeText(text);
    setStatus("字幕已复制到剪贴板", "ok");
  }

  function downloadTranscript() {
    const { title } = getMetadata();
    const blob = new Blob(["\ufeff", exportText()], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = h("a", { href: url, download: `${core.safeFilename(title)}.txt` });
    document.body.append(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    setStatus("TXT 已开始下载", "ok");
  }

  function handleError(error) {
    console.warn("[YouTube 字幕 TXT]", error);
    setStatus(error?.message || "操作失败，请刷新页面重试", "error");
  }

  function buildUi() {
    if (document.getElementById(ROOT_ID)) return;

    const closeButton = h("button", {
      className: "ytst__icon",
      type: "button",
      title: "收起",
      "aria-label": "收起字幕面板",
      "data-role": "close",
      text: "×",
    });
    const languageSelect = h("select", {
      "data-role": "language",
      "aria-label": "字幕语言",
      title: "字幕语言",
    }, [h("option", { text: "等待读取字幕" })]);
    const timestampToggle = h("input", {
      type: "checkbox",
      checked: "checked",
      "data-role": "timestamps",
    });
    const panel = h("section", { className: "ytst__panel", "aria-label": "YouTube 字幕 TXT" }, [
      h("header", { className: "ytst__header" }, [
        h("div", {}, [
          h("strong", { text: "YouTube 字幕" }),
          h("span", { text: "本地读取 · TXT 导出" }),
        ]),
        closeButton,
      ]),
      h("div", { className: "ytst__controls" }, [
        languageSelect,
        h("label", { className: "ytst__check" }, [timestampToggle, h("span", { text: "时间戳" })]),
      ]),
      h("div", { className: "ytst__actions" }, [
        h("button", { type: "button", "data-action": "reload", text: "重新读取" }),
        h("button", { type: "button", "data-action": "copy", text: "复制" }),
        h("button", { type: "button", className: "is-primary", "data-action": "download", text: "下载 TXT" }),
      ]),
      h("p", { className: "ytst__status", "data-role": "status", text: "打开面板后自动读取当前视频字幕" }),
      h("textarea", {
        className: "ytst__output",
        "data-role": "output",
        readonly: "readonly",
        spellcheck: "false",
        placeholder: "字幕将在这里显示",
      }),
    ]);
    const toggle = h("button", {
      className: "ytst__toggle",
      type: "button",
      title: "读取并下载字幕",
      "aria-label": "打开 YouTube 字幕工具",
      text: "字",
    });
    const root = h("div", { id: ROOT_ID, className: "ytst" }, [toggle, panel]);
    document.body.append(root);

    toggle.addEventListener("click", () => {
      root.classList.add("is-open");
      if (!segments.length) loadAvailableTracks().catch(handleError);
    });
    closeButton.addEventListener("click", () => root.classList.remove("is-open"));
    languageSelect.addEventListener("change", (event) => loadTrack(event.target.value).catch(handleError));
    timestampToggle.addEventListener("change", refreshOutput);
    panel.addEventListener("click", (event) => {
      const action = event.target.closest("button")?.dataset.action;
      if (action === "reload") loadAvailableTracks().catch(handleError);
      if (action === "copy") copyTranscript().catch(handleError);
      if (action === "download") {
        try { downloadTranscript(); } catch (error) { handleError(error); }
      }
    });
  }

  function resetForNavigation() {
    const videoId = getVideoId();
    if (videoId === currentVideoId) return;
    currentVideoId = videoId;
    playerResponse = null;
    tracks = [];
    segments = [];
    capturedCaptions = [];
    setOutput("");
    setStatus(isWatchPage() ? "已切换视频，打开面板读取字幕" : "请打开一个 YouTube 视频", "idle");
    document.getElementById(ROOT_ID)?.classList.toggle("is-hidden", !isWatchPage());
  }

  buildUi();
  resetForNavigation();
  window.addEventListener("yt-navigate-finish", () => setTimeout(resetForNavigation, 300));
})();
