const assert = require("node:assert/strict");
const core = require("./transcript-core.js");

const segments = core.parseJson3({
  events: [
    { tStartMs: 1000, dDurationMs: 1500, segs: [{ utf8: "Hello" }, { utf8: " world" }] },
    { tStartMs: 2500, segs: [{ utf8: "Hello world" }] },
    { tStartMs: 3661000, segs: [{ utf8: "Next\nline" }] },
  ],
});

assert.deepEqual(segments, [
  { startMs: 1000, durationMs: 1500, text: "Hello world" },
  { startMs: 3661000, durationMs: 0, text: "Next line" },
]);
assert.equal(core.buildPlainText(segments, true), "[00:01] Hello world\n[01:01:01] Next line");
assert.equal(core.buildPlainText(segments, false), "Hello world\nNext line");
assert.deepEqual(core.parseVtt("WEBVTT\n\n00:01.000 --> 00:02.500\nHello <b>world</b>\n"), [
  { startMs: 1000, durationMs: 1500, text: "Hello world" },
]);
assert.equal(core.safeFilename('A/B: C?'), "A_B_ C_");
assert.equal(core.extractTracks({ captions: { playerCaptionsTracklistRenderer: { captionTracks: [
  { baseUrl: "https://example.com", languageCode: "en", name: { simpleText: "English" }, kind: "asr" },
] } } })[0].autoGenerated, true);

console.log("transcript-core: all tests passed");
