((root, factory) => {
  const api = factory();
  root.YouTubeSubtitleCore = api;
  if (typeof module === "object" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this, () => {
  function formatTime(milliseconds) {
    const total = Math.max(0, Math.floor((Number(milliseconds) || 0) / 1000));
    const hours = Math.floor(total / 3600);
    const minutes = Math.floor((total % 3600) / 60);
    const seconds = total % 60;
    const short = `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}`;
    return hours ? `${String(hours).padStart(2, "0")}:${short}` : short;
  }

  function cleanCaptionText(value) {
    return String(value || "")
      .replace(/\n+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function parseJson3(payload) {
    const events = Array.isArray(payload?.events) ? payload.events : [];
    const segments = [];
    let previous = "";

    for (const event of events) {
      const text = cleanCaptionText(
        (Array.isArray(event.segs) ? event.segs : []).map((segment) => segment.utf8 || "").join("")
      );
      if (!text || text === previous) continue;
      previous = text;
      segments.push({
        startMs: Number(event.tStartMs) || 0,
        durationMs: Number(event.dDurationMs) || 0,
        text,
      });
    }
    return segments;
  }

  function parseVtt(source) {
    const lines = String(source || "").replace(/^\uFEFF/, "").split(/\r?\n/);
    const segments = [];
    for (let index = 0; index < lines.length; index += 1) {
      const timing = lines[index].match(/^(\d{2}:\d{2}(?::\d{2})?[.,]\d{3})\s+-->\s+(\d{2}:\d{2}(?::\d{2})?[.,]\d{3})/);
      if (!timing) continue;
      const textLines = [];
      for (index += 1; index < lines.length && lines[index].trim(); index += 1) textLines.push(lines[index]);
      const toMs = (value) => {
        const parts = value.replace(",", ".").split(":").map(Number);
        const seconds = parts.length === 3 ? parts[0] * 3600 + parts[1] * 60 + parts[2] : parts[0] * 60 + parts[1];
        return Math.round(seconds * 1000);
      };
      const text = cleanCaptionText(textLines.join(" ").replace(/<[^>]+>/g, ""));
      if (text) segments.push({ startMs: toMs(timing[1]), durationMs: Math.max(0, toMs(timing[2]) - toMs(timing[1])), text });
    }
    return segments;
  }

  function extractTracks(playerResponse) {
    const renderer = playerResponse?.captions?.playerCaptionsTracklistRenderer;
    const tracks = Array.isArray(renderer?.captionTracks) ? renderer.captionTracks : [];
    return tracks
      .filter((track) => track?.baseUrl)
      .map((track, index) => ({
        id: `${track.vssId || track.languageCode || "track"}-${index}`,
        baseUrl: track.baseUrl,
        languageCode: track.languageCode || "",
        label:
          track.name?.simpleText ||
          track.name?.runs?.map((run) => run.text).join("") ||
          track.languageCode ||
          `字幕 ${index + 1}`,
        autoGenerated: track.kind === "asr" || String(track.vssId || "").startsWith("a."),
      }));
  }

  function withFormat(baseUrl, format) {
    const url = new URL(baseUrl);
    url.searchParams.set("fmt", format);
    return url.toString();
  }

  function buildPlainText(segments, timestamps) {
    return segments
      .map((segment) => (timestamps ? `[${formatTime(segment.startMs)}] ${segment.text}` : segment.text))
      .join("\n");
  }

  function safeFilename(value) {
    const cleaned = String(value || "YouTube 字幕")
      .replace(/[\\/:*?"<>|]/g, "_")
      .replace(/\s+/g, " ")
      .trim();
    return (cleaned || "YouTube 字幕").slice(0, 120);
  }

  return { buildPlainText, cleanCaptionText, extractTracks, formatTime, parseJson3, parseVtt, safeFilename, withFormat };
});
