const sectors = [
  ['电子', '+163.08', '+2.84%', 91], ['半导体', '+88.23', '+3.16%', 82], ['通信设备', '+37.10', '+1.76%', 67], ['数字芯片设计', '+31.14', '+2.21%', 59], ['元件', '+27.66', '+1.43%', 52], ['有色金属', '+26.75', '+0.88%', 47], ['电力设备', '+26.60', '+0.64%', 43], ['通信服务', '+25.33', '+0.58%', 39], ['汽车零部件', '-12.84', '-0.52%', 32], ['电力', '-13.56', '-0.44%', 28], ['白酒Ⅱ', '-14.53', '-0.71%', 24], ['食品饮料', '-20.27', '-0.83%', 21]];
const colors = ['#b84f53','#c56564','#d27a54','#d89154','#cba05c','#e0b66b','#8f9f61','#719d84','#327c70','#3b7180','#4b7687','#54847c'];
const state = { paused:false, range:'today', unit:'hundred', tick:0, hoverIndex:null };
const $ = (id) => document.getElementById(id);
function renderSectors(){ $('sectorList').innerHTML = sectors.slice(0, 7).map((s,i)=>`<div class="sector-row"><div class="sector-name"><span class="sector-index">0${i+1}</span><b>${s[0]}</b></div><span class="flow-num ${s[1][0]==='-'?'negative':'positive'}">${s[1]}</span><span class="change ${s[2][0]==='-'?'negative':'positive'}">${s[2]}</span><span class="mini-bar"><i class="${s[1][0]==='-'?'out':''}" style="width:${s[3]}%"></i></span></div>`).join(''); }
function renderLegend(){ $('legend').innerHTML = sectors.slice(0, 8).map((s,i)=>`<span class="legend-item"><i style="background:${colors[i]}"></i>${s[0]}</span>`).join(''); }
function makeSeries(i, count){ const values=[]; let v=0; for(let j=0;j<count;j++){ const t=j/(count-1); const wave=Math.sin(j*.33+i*1.7)*2.8+Math.sin(j*.11+i)*3; const lift=i<2 ? (t>0.45?(t-.45)*170:(t-.45)*20) : (i<6 ? (t-.4)*34 : -(t-.35)*23); const shock=(i===0&&t>.52?44:0)+(i===1&&t>.52?25:0); v=(lift+wave+shock)*(0.75+((i*3)%5)/10); values.push(v); } return values; }
function drawChart(){ const wrap=$('chartWrap'), canvas=$('flowChart'), dpr=window.devicePixelRatio||1, w=wrap.clientWidth, h=wrap.clientHeight; canvas.width=w*dpr; canvas.height=h*dpr; const ctx=canvas.getContext('2d'); ctx.scale(dpr,dpr); const pad={l:48,r:18,t:18,b:30}, cw=w-pad.l-pad.r, ch=h-pad.t-pad.b; const max=200,min=-150; const x=(i,n)=>pad.l+(i/(n-1))*cw; const y=(v)=>pad.t+(max-v)/(max-min)*ch; ctx.clearRect(0,0,w,h); ctx.font='11px "DM Mono"'; ctx.textAlign='right'; for(let v=-150;v<=200;v+=50){ const yy=y(v); ctx.strokeStyle=v===0?'#7c9690':'#e0e8e4'; ctx.lineWidth=v===0?1.1:1; ctx.setLineDash(v===0?[]:[3,3]); ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#82908c';ctx.fillText(v===0?'0':`${v>0?'':'-'}${Math.abs(v)}亿`,pad.l-8,yy+4); } const hours=['09:30','10:00','10:30','11:00','11:30','13:00','13:30','14:00','14:30','15:00']; ctx.textAlign='center'; hours.forEach((label,i)=>{const xx=pad.l+i/(hours.length-1)*cw;ctx.strokeStyle='#eef2f0';ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillStyle='#82908c';ctx.fillText(label,xx,h-9)}); const n=state.range==='today'?90:state.range==='week'?55:40; sectors.forEach((s,i)=>{const vals=makeSeries(i,n);ctx.strokeStyle=colors[i];ctx.lineWidth=i<2?2.1:1.45;ctx.beginPath();vals.forEach((v,j)=>{const xx=x(j,n),yy=y(v);j?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke(); if(state.hoverIndex!==null&&i<8){const j=Math.min(n-1,state.hoverIndex);ctx.fillStyle=colors[i];ctx.beginPath();ctx.arc(x(j,n),y(vals[j]),3,0,Math.PI*2);ctx.fill();} }); if(state.hoverIndex!==null){const xx=x(state.hoverIndex,n);ctx.strokeStyle='rgba(33,70,60,.25)';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.setLineDash([]);} }
function updateNumbers(){ if(state.paused)return; state.tick++; const n=(v,delta=1)=> (v+Math.sin(state.tick/3)*delta).toFixed(1); $('totalFlow').textContent=`+${n(1286.4,4)}`;$('largeOrder').textContent=`+${n(624.8,2)}`;$('upCount').textContent=Math.round(2841+Math.sin(state.tick/4)*13).toLocaleString();$('downCount').textContent=Math.round(1724+Math.cos(state.tick/4)*8).toLocaleString();$('breadth').textContent=(1.65+Math.sin(state.tick/5)*.02).toFixed(2); const now=new Date();$('lastUpdated').textContent=now.toLocaleTimeString('zh-CN',{hour12:false});drawChart(); }
function init(){ renderSectors();renderLegend();drawChart();setInterval(updateNumbers,3000);window.addEventListener('resize',drawChart);$('pauseButton').onclick=()=>{state.paused=!state.paused;$('pauseLabel').textContent=state.paused?'继续更新':'暂停更新';document.querySelector('.pause-icon').textContent=state.paused?'▶':'Ⅱ';}; document.querySelectorAll('.time-tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.time-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.range=btn.dataset.range;drawChart();});$('unitSelect').onchange=(e)=>{state.unit=e.target.value;}; $('themeToggle').onclick=()=>document.body.classList.toggle('dark');$('flowChart').addEventListener('mousemove',(event)=>{const rect=event.currentTarget.getBoundingClientRect(),w=rect.width,n=state.range==='today'?90:state.range==='week'?55:40;state.hoverIndex=Math.max(0,Math.min(n-1,Math.round((event.clientX-48)/(w-66)*(n-1))));const tip=$('chartTooltip');tip.style.display='block';tip.style.left=`${Math.min(event.clientX-rect.left+14,w-155)}px`;tip.style.top=`${Math.max(18,event.clientY-rect.top-70)}px`;tip.innerHTML=`<b>${['09:30','10:30','11:30','13:00','14:00','15:00'][Math.min(5,Math.round(state.hoverIndex/(n-1)*5))]}</b><br>主力净流入　<span class="positive">+${(1286+state.hoverIndex*1.7).toFixed(1)} 亿</span>`;drawChart();});$('flowChart').addEventListener('mouseleave',()=>{state.hoverIndex=null;$('chartTooltip').style.display='none';drawChart();});$('addWatch').onclick=()=>alert('自选监控已准备就绪');}init();
