const colors = ['#b84f53','#c56564','#d27a54','#d89154','#cba05c','#e0b66b','#8f9f61','#719d84','#327c70','#3b7180','#4b7687','#54847c'];
const state = { paused:false, range:'today', unit:'hundred', hoverIndex:null, data:null, error:null };
const $ = (id) => document.getElementById(id);
const fallbackNames = ['电子','半导体','通信设备','数字芯片设计','元件','有色金属','电力设备','通信服务'];
function formatFlow(value){ const unit = state.unit === 'billion' ? value / 10 : value; return `${unit >= 0 ? '+' : ''}${unit.toFixed(2)}`; }
function renderSectors(){ const sectors=state.data?.sectors||[]; $('sectorList').innerHTML = sectors.slice(0,7).map((s,i)=>`<div class="sector-row"><div class="sector-name"><span class="sector-index">${String(i+1).padStart(2,'0')}</span><b>${s.name}</b></div><span class="flow-num ${s.flow<0?'negative':'positive'}">${formatFlow(s.flow)}</span><span class="change ${s.changePct<0?'negative':'positive'}">${s.changePct>=0?'+':''}${s.changePct.toFixed(2)}%</span><span class="mini-bar"><i class="${s.flow<0?'out':''}" style="width:${Math.min(100,Math.max(8,Math.abs(s.flow)/(Math.abs(sectors[0]?.flow||1))*100))}%"></i></span></div>`).join(''); }
function renderLegend(){ const series=state.data?.series||[]; $('legend').innerHTML = (series.length?series.map((s,i)=>`<span class="legend-item"><i style="background:${colors[i]}"/>${s.name}</span>`):fallbackNames.map((name,i)=>`<span class="legend-item"><i style="background:${colors[i]}"/>${name}</span>`)).join(''); }
function renderWatchlist(){ const items=state.data?.watchlist||[]; $('watchList').innerHTML=items.length?items.map(item=>`<div class="watch-item"><div><b>${item.name}</b><small>${item.code} · ${item.sector}</small></div><strong class="${item.changePct<0?'negative':'positive'}">${item.changePct>=0?'+':''}${Number(item.changePct).toFixed(2)}%</strong></div>`).join(''):'<div class="watch-empty">等待实时行情</div>'; }
function drawChart(){ const wrap=$('chartWrap'), canvas=$('flowChart'), dpr=window.devicePixelRatio||1, w=wrap.clientWidth, h=wrap.clientHeight; canvas.width=w*dpr; canvas.height=h*dpr; const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const pad={l:48,r:18,t:18,b:30},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;ctx.clearRect(0,0,w,h);ctx.font='11px "DM Mono"';ctx.textAlign='right'; const samples=state.data?.series?.[0]?.points||[], values=(state.data?.series||[]).flatMap(s=>s.points.map(p=>p.value)); const max=Math.max(50,...values,0),min=Math.min(-50,...values,0), step=Math.max(25,Math.ceil(Math.max(Math.abs(max),Math.abs(min))/4/25)*25), top=Math.ceil(max/step)*step,bottom=Math.floor(min/step)*step;const y=(v)=>pad.t+(top-v)/(top-bottom)*ch;const x=(i,n)=>pad.l+(i/Math.max(1,n-1))*cw;for(let v=bottom;v<=top;v+=step){const yy=y(v);ctx.strokeStyle=v===0?'#7c9690':'#e0e8e4';ctx.lineWidth=v===0?1.1:1;ctx.setLineDash(v===0?[]:[3,3]);ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#82908c';ctx.fillText(v===0?'0':`${v>0?'':'-'}${Math.abs(v)}亿`,pad.l-8,yy+4);}const times=samples.map(p=>p.time), labels=times.length?[times[0],times[Math.floor(times.length/3)]||'',times[Math.floor(times.length*2/3)]||'',times[times.length-1]]:['等待实时采样'];ctx.textAlign='center';labels.forEach((label,i)=>{const xx=pad.l+(i/Math.max(1,labels.length-1))*cw;ctx.strokeStyle='#eef2f0';ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillStyle='#82908c';ctx.fillText(label,xx,h-9)});(state.data?.series||[]).forEach((series,i)=>{const points=series.points;ctx.strokeStyle=colors[i];ctx.lineWidth=i<2?2.1:1.45;ctx.beginPath();points.forEach((point,j)=>{const xx=x(j,points.length),yy=y(point.value);j?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke();if(state.hoverIndex!==null&&points[state.hoverIndex]){ctx.fillStyle=colors[i];ctx.beginPath();ctx.arc(x(state.hoverIndex,points.length),y(points[state.hoverIndex].value),3,0,Math.PI*2);ctx.fill();}});if(state.hoverIndex!==null&&samples[state.hoverIndex]){const xx=x(state.hoverIndex,samples.length);ctx.strokeStyle='rgba(33,70,60,.25)';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.setLineDash([]);}}
function renderMetrics(){ const metrics=state.data?.metrics||{};$('totalFlow').textContent=metrics.totalFlow==null?'--':formatFlow(metrics.totalFlow);$('largeOrder').textContent=metrics.largeOrder==null?'--':formatFlow(metrics.largeOrder);$('upCount').textContent=metrics.upCount==null?'--':metrics.upCount;$('downCount').textContent=metrics.downCount==null?'--':metrics.downCount;$('breadth').textContent=metrics.upCount&&metrics.downCount?(metrics.upCount/metrics.downCount).toFixed(2):'--';$('lastUpdated').textContent=state.data?.asOf||'等待连接';$('chartStatus').textContent=state.data?.sampleCount?`已采集 ${state.data.sampleCount} 个实时样本`:'等待首个实时样本';$('dataSource').textContent=state.data?.stale?'东方财富短时限流，展示最近真实数据':state.data?.live?'数据来源：东方财富公开行情':'行情源连接失败';}
function renderAll(){renderSectors();renderLegend();renderWatchlist();renderMetrics();drawChart();}
async function loadData(){if(state.paused)return;try{const response=await fetch(`/api/flow?range=${state.range}`,{cache:'no-store'});if(!response.ok)throw new Error('行情源暂时不可用');state.data=await response.json();state.error=null;}catch(error){state.error=error;$('dataSource').textContent='实时行情连接失败，请检查本地服务';}renderAll();}
function tooltipFor(index){ const series=state.data?.series||[], sample=series[0]?.points?.[index];if(!sample)return '';return `<b>${sample.time}</b>${series.map((s,i)=>{const point=s.points[index];return point?`<br><span style="color:${colors[i]}">●</span> ${s.name}　<span class="${point.value<0?'negative':'positive'}">${formatFlow(point.value)} ${state.unit==='billion'?'十亿元':'亿元'}</span>`:''}).join('')}`; }
function init(){renderAll();setInterval(loadData,3000);loadData();window.addEventListener('resize',drawChart);$('pauseButton').onclick=()=>{state.paused=!state.paused;$('pauseLabel').textContent=state.paused?'继续更新':'暂停更新';document.querySelector('.pause-icon').textContent=state.paused?'▶':'Ⅱ';};document.querySelectorAll('.time-tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.time-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.range=btn.dataset.range;loadData();});$('unitSelect').onchange=(event)=>{state.unit=event.target.value;renderAll();};$('themeToggle').onclick=()=>document.body.classList.toggle('dark');$('flowChart').addEventListener('mousemove',(event)=>{const rect=event.currentTarget.getBoundingClientRect(),points=state.data?.series?.[0]?.points||[];if(!points.length)return;state.hoverIndex=Math.max(0,Math.min(points.length-1,Math.round((event.clientX-48)/(rect.width-66)*(points.length-1))));const tip=$('chartTooltip');tip.style.display='block';tip.style.left=`${Math.min(event.clientX-rect.left+14,rect.width-240)}px`;tip.style.top=`${Math.max(18,event.clientY-rect.top-125)}px`;tip.innerHTML=tooltipFor(state.hoverIndex);drawChart();});$('flowChart').addEventListener('mouseleave',()=>{state.hoverIndex=null;$('chartTooltip').style.display='none';drawChart();});$('addWatch').onclick=()=>alert('自选监控已准备就绪');}init();
